#!/user/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'runit'
cookbook 'nginx', git: 'git://github.com/opscode-cookbooks/nginx.git'

cookbook "bash-completion"
cookbook "redmine"
#cookbook "build-essential"

#cookbook "application"
#cookbook "application_ruby"
#cookbook "curl"
#cookbook "git"
#cookbook "htop"
#cookbook "imagemagick"


#cookbook "aws"

#cookbook "datadog",
#         git: "https://github.com/DataDog/chef-datadog"
#cookbook "denyhosts",
#         git: "https://github.com/phlipper/chef-denyhosts"
#cookbook "grc"
#cookbook "hostname", "~> 0.1.0"
#cookbook "iftop"
#cookbook "iptables",
#         git: "https://github.com/phlipper/iptables"
#cookbook "jenkins"
#cookbook "logrotate"
#cookbook "logwatch"
#cookbook "memcached"
#cookbook "monit",
#         git: "https://github.com/phlipper/chef-monit"
#cookbook "munin"
#cookbook "newrelic-sysmond", "~> 1.3.0"
#cookbook "nginx",
#         git: "https://github.com/phlipper/chef-nginx"
#cookbook "nodejs",
#         git: "https://github.com/phlipper/chef-nodejs"
#cookbook "ntp"
#cookbook "openssh"
#cookbook "papertrail-rsyslog"
#cookbook "postfix"
#cookbook "postgresql",
#         git: "https://github.com/phlipper/chef-postgresql"
#cookbook "redis",
#         git: "https://github.com/phlipper/chef-redis"
#cookbook "java"
#cookbook "elasticsearch",
#         git: "https://github.com/elasticsearch/cookbook-elasticsearch"
#cookbook "rbenv",
#         git: "https://github.com/fnichol/chef-rbenv"
#cookbook "resolver", '~> 1.1.4'
#cookbook "ruby_build"
#cookbook "rsync"
#cookbook "screen"
#cookbook "sudo"
#cookbook "sysstat"
#cookbook "user",
#         git: "https://github.com/fnichol/chef-user"
#cookbook "xml"
#cookbook "xslt"
#cookbook "xfs"
#cookbook "zlib"
#cookbook "vim"